name: dsanotes
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # add injectable to your dependencies  
  injectable:  
  # add get_it  
  get_it:  
  flutter_sound: ^9.2.13
  audio_session: ^0.1.16
  permission_handler: ^10.3.0
  provider: ^6.0.5
  path_provider: ^2.0.15
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.0
  intl: ^0.18.1
  draggable_bottom_sheet: ^1.0.2
  just_audio: ^0.9.31
  just_audio_background: ^0.0.1-beta.9
  audio_video_progress_bar: ^1.0.1
  animated_icon: ^0.0.5
  flutter_animate: ^4.1.1+1
  video_player: ^2.6.1
  url_launcher: ^6.1.11
  image_picker: ^0.8.4+4
  file_picker: ^4.3.0
  dynamic_color: ^1.6.5
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  injectable_generator:  
  # add build runner if not already added  
  build_runner: ^2.3.3 
  freezed: ^2.3.5
  json_serializable: ^6.6.2

flutter:
  uses-material-design: true
